version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: guest_name
      POSTGRES_USER: guest_user
      POSTGRES_PASSWORD: guest_password
    ports:
      - "5432:5432"

  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
